'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace UI.App

    Partial Public Class Lure

        '''<summary>
        '''plcLure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plcLure As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''litLure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litLure As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lnkVote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkVote As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''litExpiryDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litExpiryDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''plcAdminLoggedOn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plcAdminLoggedOn As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace
