'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace UI.App

    Partial Public Class Vote

        '''<summary>
        '''plcQuestion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plcQuestion As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''litQuestion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litQuestion As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''plcVote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plcVote As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''rbYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbYes As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''litYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litYes As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rbNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbNo As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''litNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litNo As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litExpires control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litExpires As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''btnOK control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''plcAlreadyVoted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plcAlreadyVoted As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''litAlreadyVoted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAlreadyVoted As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''plcNoActiveVotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plcNoActiveVotes As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''plcVoteFailed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plcVoteFailed As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''plcException control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plcException As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''litException control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litException As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''plcAdminLoggedOn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plcAdminLoggedOn As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''plcNonNurseMember control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plcNonNurseMember As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace
